In [1]:
import pandas as pd
import plotly.express as px

product_df = pd.DataFrame({
    "product": [
        "노트북",
        "모니터",
        "키보드",
        "마우스",
        "태블릿",
        "헤드셋",
        "웹캠",
        "스피커",
        "SSD",
        "스마트폰",
    ],
    "department": [
        "컴퓨팅",
        "컴퓨팅",
        "컴퓨팅",
        "컴퓨팅",
        "모바일",
        "컴퓨팅",
        "컴퓨팅",
        "컴퓨팅",
        "컴퓨팅",
        "모바일",
    ],
    "category": [
        "PC",
        "PC",
        "주변기기",
        "주변기기",
        "태블릿",
        "주변기기",
        "주변기기",
        "주변기기",
        "저장장치",
        "스마트폰",
    ],
    "sales": [
        320, 210, 150, 110, 260,
        140, 90, 120, 180, 360,
    ],
    "profit": [
        72, 48, 41, 28, 58,
        35, 21, 26, 46, 81,
    ],
    "customers": [
        120, 95, 150, 170, 105,
        130, 75, 100, 115, 140,
    ],
    "satisfaction": [
        4.6, 4.3, 4.5, 4.2, 4.7,
        4.1, 4.0, 4.3, 4.5, 4.8,
    ],
})

print(product_df)

  product department category  sales  profit  customers  satisfaction
0     노트북        컴퓨팅       PC    320      72        120           4.6
1     모니터        컴퓨팅       PC    210      48         95           4.3
2     키보드        컴퓨팅     주변기기    150      41        150           4.5
3     마우스        컴퓨팅     주변기기    110      28        170           4.2
4     태블릿        모바일      태블릿    260      58        105           4.7
5     헤드셋        컴퓨팅     주변기기    140      35        130           4.1
6      웹캠        컴퓨팅     주변기기     90      21         75           4.0
7     스피커        컴퓨팅     주변기기    120      26        100           4.3
8     SSD        컴퓨팅     저장장치    180      46        115           4.5
9    스마트폰        모바일     스마트폰    360      81        140           4.8

In [2]:
heatmap_df = pd.DataFrame(
    [
        [120, 150, 180, 210],
        [90, 110, 130, 160],
        [70, 95, 105, 125],
    ],
    index=[
        "PC",
        "모바일",
        "주변기기",
    ],
    columns=[
        "1월",
        "2월",
        "3월",
        "4월",
    ],
)

print(heatmap_df)

       1월   2월   3월   4월
PC    120  150  180  210
모바일    90  110  130  160
주변기기   70   95  105  125

In [3]:
fig = px.imshow(
    heatmap_df,
    text_auto=True,
    aspect='auto',
    labels={
        'x': '월',
        'y': '카테고리',
        'color': '매출'
    }
)

fig.show()

In [4]:
fig = px.imshow(
    heatmap_df,
    text_auto=True,
    aspect='auto',
    labels={
        'x': '월',
        'y': '카테고리',
        'color': '매출'
    },
    color_continuous_scale='Blues'
)

fig.show()

In [5]:
product_df.columns.to_list()

['product',
 'department',
 'category',
 'sales',
 'profit',
 'customers',
 'satisfaction']

In [6]:
numeric_df = product_df[
    [
        'sales',
        'profit',
        'customers',
        'satisfaction'
    ]
]

numeric_df.head()

   sales  profit  customers  satisfaction
0    320      72        120           4.6
1    210      48         95           4.3
2    150      41        150           4.5
3    110      28        170           4.2
4    260      58        105           4.7

In [10]:
corr_df = numeric_df.corr().round(2)

corr_df

              sales  profit  customers  satisfaction
sales          1.00    0.99       0.09          0.85
profit         0.99    1.00       0.17          0.87
customers      0.09    0.17       1.00          0.23
satisfaction   0.85    0.87       0.23          1.00

상관계수 행렬

- 양수 1에 가까울수록: 강한 양의 선형 관계
- 0에 가까울수록: 선형 관계가 약하다
- 음수 1에 가까울수록: 강한 음의 선형 관계

In [11]:
fig = px.imshow(
    corr_df,
    text_auto='.2f',
    zmin=-1,
    zmax=1,
    color_continuous_scale='RdBu_r'
)

fig.show()