In [1]:
import pandas as pd
import plotly.express as px

monthly_df = pd.DataFrame({
    "date": pd.date_range(
        start="2026-01-01",
        periods=12,
        freq="MS",
    ),
    "sales": [
        120, 135, 128, 150,
        165, 172, 168, 185,
        198, 210, 205, 225,
    ],
})

print(monthly_df)

         date  sales
0  2026-01-01    120
1  2026-02-01    135
2  2026-03-01    128
3  2026-04-01    150
4  2026-05-01    165
5  2026-06-01    172
6  2026-07-01    168
7  2026-08-01    185
8  2026-09-01    198
9  2026-10-01    210
10 2026-11-01    205
11 2026-12-01    225

In [2]:
fig = px.line(
    monthly_df,
    x='date',
    y='sales',
)

fig.show()

In [4]:
monthly_df['change'] = monthly_df['sales'].diff()

In [5]:
monthly_df

         date  sales  change
0  2026-01-01    120     NaN
1  2026-02-01    135    15.0
2  2026-03-01    128    -7.0
3  2026-04-01    150    22.0
4  2026-05-01    165    15.0
5  2026-06-01    172     7.0
6  2026-07-01    168    -4.0
7  2026-08-01    185    17.0
8  2026-09-01    198    13.0
9  2026-10-01    210    12.0
10 2026-11-01    205    -5.0
11 2026-12-01    225    20.0

In [7]:
unsorted_df = pd.DataFrame({
    "date": pd.to_datetime([
        "2026-01-01",
        "2026-03-01",
        "2026-02-01",
        "2026-05-01",
        "2026-04-01",
    ]),
    "sales": [
        120,
        128,
        135,
        165,
        150,
    ],
})

print(unsorted_df)

        date  sales
0 2026-01-01    120
1 2026-03-01    128
2 2026-02-01    135
3 2026-05-01    165
4 2026-04-01    150

In [8]:
fig = px.line(
    unsorted_df,
    x='date',
    y='sales',
    markers=True,
)

fig.show()

In [9]:
sorted_df = unsorted_df.sort_values('date')

sorted_df

        date  sales
0 2026-01-01    120
2 2026-02-01    135
1 2026-03-01    128
4 2026-04-01    150
3 2026-05-01    165

In [10]:
fig = px.line(
    sorted_df,
    x='date',
    y='sales',
    markers=True,
)

fig.show()

```python
df = read_csv(...)

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')
```

In [11]:
category_df = pd.DataFrame({
    "date": pd.to_datetime([
        "2026-01-01", "2026-02-01", "2026-03-01",
        "2026-04-01", "2026-05-01", "2026-06-01",

        "2026-01-01", "2026-02-01", "2026-03-01",
        "2026-04-01", "2026-05-01", "2026-06-01",

        "2026-01-01", "2026-02-01", "2026-03-01",
        "2026-04-01", "2026-05-01", "2026-06-01",
    ]),
    "category": (
        ["PC"] * 6
        + ["모바일"] * 6
        + ["주변기기"] * 6
    ),
    "sales": [
        180, 195, 205, 220, 235, 250,
        140, 150, 165, 180, 205, 225,
        100, 108, 115, 125, 130, 142,
    ],
})

print(category_df)

         date category  sales
0  2026-01-01       PC    180
1  2026-02-01       PC    195
2  2026-03-01       PC    205
3  2026-04-01       PC    220
4  2026-05-01       PC    235
5  2026-06-01       PC    250
6  2026-01-01      모바일    140
7  2026-02-01      모바일    150
8  2026-03-01      모바일    165
9  2026-04-01      모바일    180
10 2026-05-01      모바일    205
11 2026-06-01      모바일    225
12 2026-01-01     주변기기    100
13 2026-02-01     주변기기    108
14 2026-03-01     주변기기    115
15 2026-04-01     주변기기    125
16 2026-05-01     주변기기    130
17 2026-06-01     주변기기    142

In [13]:
fig = px.line(
    category_df,
    x='date',
    y='sales',
    markers=True,
)

fig.show()

In [14]:
fig = px.line(
    category_df,
    x='date',
    y='sales',
    color='category',
    markers=True,
)

fig.show()

In [15]:
fig = px.line(
    category_df,
    x='date',
    y='sales',
    color='category',
    symbol='category',
    markers=True,
)

fig.show()

## 영역 그래프(Area Graph)

- 선그래프: 방향과 추세
- 영역그래프: 변화 + 값의 규모

In [16]:
fig = px.area(
    monthly_df,
    x='date',
    y='sales'
)

fig